### ISSUE TITLE
TacoToken Bounty

### ISSUE THREAD

**Issue by vmichalik** [jaredpereira/playground#4]
Do you understand what Fathom is?
- Yes. 

Do you understand what Playground is (please summarize it in a few lines as if you were explaining to someone who doesn't know about it)
- Playground is a loosely-knit community experiment in which several contributors will propose, receive funds for and then undertake a self-defined learning journey in distributed systems. The goal is to explore and iterate upon different learning models and environments.

Can you give suggestions on how to make it clearer?
-The "inspiration" line above section 2 is very useful and might be highlighted closer to the top of the article to give a better framework for understanding the following points.

0x5a642BFf25434720A2aE6cB43677A32A25361193

**Comment by jaredpereira** [comment]
Awesome! Thanks for the feedback :). Implemented in 0dc7aa6f56abc7b4956228248130f1cfe3410f5a

**Comment by joelamouche** [comment]
@vmichalik thanks for the feedback, taco tokens coming your way :)
